title: Mourya Boggarapa # your name (or website title) here
logo: "/images/DSC_1003.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  ML Engineer at Sambanova, Masters Degree at Carnegie Mellon University's School of Computer Science. I have over 6 years of industry experience. I primarily work on Machine Learning Systems, I also work on back-end systems, mobile app development and UI/UX.
  <br><br>
  I am an avid photographer who likes to shoot landscapes, architecture, and nature.  
  <br><br>
  <a href="https://www.linkedin.com/in/mouryabs">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
